---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: setup mirror
      copy: src=./sources.list dest=/etc/apt/sources.list mode=644
    - apt_key: url={{ item }} state=present
      with_items:
        - https://jenkins-ci.org/debian/jenkins-ci.org.key
        - https://dl.google.com/linux/linux_signing_key.pub
    - name: setup 3rd party mirrors
      copy: src=./jenkins/{{ item }}.list dest=/etc/apt/sources.list.d/{{ item }}.list mode=644
      with_items:
        - jenkins
        - chrome
    - apt: update_cache=yes
    - name: install jenkins
      apt: pkg=jenkins state=present
    - file: path=/usr/share/jenkins/ref/plugins state=directory
    - apt: pkg=unzip state=present
    - name: install jenkins plugins
      get_url:
        url: https://updates.jenkins-ci.org/download/plugins/{{ item }}/latest/{{ item }}.hpi
        dest: /var/lib/jenkins/plugins/{{ item }}.jpi
      with_items:
        - greenballs
        - ansicolor
        - robot
        - xvfb
      register: plugins
    - name: restart jenkins
      service: name=jenkins state=restarted
      when: plugins.changed
    - name: install python pip
      apt: pkg=python-pip state=present
    - name: install robotframework and selenium library
      pip: name={{ item }}
      with_items:
        - robotframework
        - robotframework-selenium2library
    - name: install headless browser
      apt: pkg={{ item }} state=present
      with_items:
        - google-chrome-stable
        - xvfb
    - name: install chrome driver
      unarchive:
        src: http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
        dest: /usr/bin
        copy: no
        mode: 0511
