---
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: setup mirror
      copy: src=./sources.list dest=/etc/apt/sources.list mode=644
    - apt_key: url=https://jenkins-ci.org/debian/jenkins-ci.org.key state=present
    - name: setup jenkins mirror
      copy: src=./jenkins/jenkins.list dest=/etc/apt/sources.list.d/jenkins.list mode=644
    - apt: update_cache=yes
    - name: install jenkins
      apt: pkg=jenkins state=present
    - file: path=/usr/share/jenkins/ref/plugins state=directory
    - apt: pkg=unzip state=present
    - name: install jenkins plugins
      get_url: url=https://updates.jenkins-ci.org/download/plugins/{{ item }}/latest/{{ item }}.hpi dest=/var/lib/jenkins/plugins/{{ item }}.jpi
      with_items:
        - greenballs
        - ansicolor
        - robot
        - xvfb
    - name: restart jenkins
      service: name=jenkins state=restarted
    - name: install python pip
      apt: pkg=python-pip state=present
    - name: install robotframework and selenium library
      pip: name={{ item }}
      with_items:
        - robotframework
        - robotframework-selenium2library
